// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function VanInventory(props) {
//   const { nodes, materials } = useGLTF(
//     '/models/vanInventory.glb'
//   )
//   console.log(nodes,"nodes")
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube040.geometry}
//         material={materials['Stained bamboo']}
//         position={[-550.371, 1498.829, -273.599]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.boot_side.geometry}
//         material={materials.carpaint}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.boot_detail.geometry}
//         material={materials.black}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.side_door.geometry}
//         material={materials['Material.020']}
//         position={[-1125.446, 1177.362, -2137.772]}
//         rotation={[0, 0, 0]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Blue02.geometry}
//         material={materials.blueglass}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Box_support.geometry}
//         material={materials.mattemetal}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.door_front_left_lamp.geometry}
//         material={materials.clearglass}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.door_front_left_lock02.geometry}
//         material={materials.chrome}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.door_front_left_Mirror.geometry}
//         material={materials.mirror}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <group position={[1.448, -166.742, 79.589]} scale={[1023.136, 1033.378, 1033.378]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.door_front_R_Glass_1.geometry}
//           material={materials.white}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.door_front_R_Glass_2.geometry}
//           material={materials.interior_third}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.door_front_R_Glass_3.geometry}
//           material={materials.glass}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.door_front_R_Glass_4.geometry}
//           material={materials.Material}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.gage_panel_light.geometry}
//         material={materials.interior_second}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.indicator_panel_needle.geometry}
//         material={materials.red}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <group position={[1.448, -166.742, 79.589]} scale={[1023.136, 1033.378, 1033.378]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.interior_floor.geometry}
//           material={materials['interior_second.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.interior_floor_1.geometry}
//           material={materials['interior_sixth.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.interior_floor_2.geometry}
//           material={materials['carpaint.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.interior_floor_3.geometry}
//           material={materials['black.001']}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.level01.geometry}
//         material={materials.blue}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Orange_glass.geometry}
//         material={materials.orangeglass}
//         position={[1.448, -166.742, 79.589]}
//         scale={[1023.136, 1033.378, 1033.378]}
//       />
//       <group position={[1.448, -166.742, 79.589]} scale={[1023.136, 1033.378, 1033.378]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.steering_switch_text_1.geometry}
//           material={materials.interior_fourth}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.steering_switch_text_2.geometry}
//           material={materials.interior_seventh}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.steering_switch_text_3.geometry}
//           material={materials.interior_sixth}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.steering_switch_text_4.geometry}
//           material={materials.interior_fifth}
//         />
//       </group>
//       <group
//         position={[866.617, 1331.595, -2810.675]}
//         rotation={[0, -Math.PI / 2, 0]}
//         scale={[1033.378, 1033.378, 1023.136]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.body_part10005.geometry}
//           material={materials.LicPlate_yellow}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.body_part10005_1.geometry}
//           material={materials.LicPlate_black}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.body_part10005_2.geometry}
//           material={materials.LicPlate_blue}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.body_part10005_3.geometry}
//           material={materials.LicPlate_white}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.body_part10005_4.geometry}
//           material={materials.yellow}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.body_part10005_5.geometry}
//           material={materials['White (Gel Stain on Maple)']}
//         />
//       </group>
//       <group position={[-592.794, 1456.671, 114.845]} rotation={[Math.PI, 0, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['����������1_1'].geometry}
//           material={materials['Material.006']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['����������1_2'].geometry}
//           material={materials.Metal}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['����������1_3'].geometry}
//           material={materials['Stormy Sea (DE 5817)']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['����������1_4'].geometry}
//           material={materials['Material.074']}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.EFI71.geometry}
//         material={materials['Bone China DEW 339']}
//         position={[-713.743, 2283.93, -1066.583]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={[1.005, 1.436, 1.024]}
//       />
//       <group
//         position={[-785.002, 2057.761, -800.114]}
//         rotation={[Math.PI, -0.003, Math.PI]}
//         scale={[1059.384, 1023.685, 976.599]}>
//         <mesh castShadow receiveShadow geometry={nodes.Mesh044.geometry} material={materials.CP} />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_1.geometry}
//           material={materials['Bone China DEW 339']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_2.geometry}
//           material={materials['White (Gel Stain on Maple)']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_3.geometry}
//           material={materials['Stormy Sea (DE 5817)']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_4.geometry}
//           material={materials['Antique Wallnut (Gel Stain on Maple)']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_5.geometry}
//           material={materials['Stained bamboo']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_6.geometry}
//           material={materials.Bleck_S}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh044_7.geometry}
//           material={materials.Metal}
//         />
//       </group>
//       <group
//         position={[590.113, 2320.561, -376.935]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={[1.136, 1.135, 1.129]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Объект_7_1.geometry}
//           material={materials.Cabinets}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Объект_7_2.geometry}
//           material={materials['W Light']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Объект_7_3.geometry}
//           material={materials['White (GEL STAIN ON MAPLE).002']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Объект_7_4.geometry}
//           material={materials['Wooden .002']}
//         />
//       </group>
//       <group
//         position={[853.547, 1667.561, -114.706]}
//         rotation={[0.016, 0, 1.641]}
//         scale={[-1.129, -0.102, -1.129]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane008.geometry}
//           material={materials['black.006']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane008_1.geometry}
//           material={materials.Galsss01}
//         />
//       </group>
//       <group
//         position={[13.988, 2496.634, -788.704]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[1.129, 1.136, 1.129]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane031.geometry}
//           material={materials['black.010']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane031_1.geometry}
//           material={materials['W Light.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane031_2.geometry}
//           material={materials['Antique Wallnut (Gel Stain on Maple)']}
//         />
//       </group>
//       <group
//         position={[8.374, 2721.975, -2287.198]}
//         rotation={[1.587, 0, 0.006]}
//         scale={[0.896, 1.156, 0.861]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001'].geometry}
//           material={materials['Ekran_Resmi_2020-07-10_11.50.07_kopyası']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_1'].geometry}
//           material={materials['[Metal_Corrogated_Shiny]2']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_2'].geometry}
//           material={materials['Simple wood.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_3'].geometry}
//           material={materials['Material.002']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_4'].geometry}
//           material={materials['Material.009']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_5'].geometry}
//           material={materials['white.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_6'].geometry}
//           material={materials.black_rubber}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_7'].geometry}
//           material={materials['Metal_Mesh_Grid.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_8'].geometry}
//           material={materials['Material.003']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_9'].geometry}
//           material={materials['Material.008']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_10'].geometry}
//           material={materials['Material.007']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_11'].geometry}
//           material={materials['New ac']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_12'].geometry}
//           material={materials['Material.038']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_13'].geometry}
//           material={materials.glass}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-Component#16001_14'].geometry}
//           material={materials['black.006']}
//         />
//       </group>
//       <group position={[864.828, 520.594, -2585.567]} rotation={[-1.562, 0, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0.geometry}
//           material={materials.Floor}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_1.geometry}
//           material={materials.black}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_2.geometry}
//           material={materials.redglass}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_3.geometry}
//           material={materials.chrome}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_4.geometry}
//           material={materials.carpaint}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_5.geometry}
//           material={materials.clearglass}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_6.geometry}
//           material={materials.LicPlate_yellow}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_7.geometry}
//           material={materials.LicPlate_black}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_8.geometry}
//           material={materials.LicPlate_blue}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_9.geometry}
//           material={materials.LicPlate_white}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_10.geometry}
//           material={materials.yellow}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_11.geometry}
//           material={materials.interior_second}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_0_12.geometry}
//           material={materials['black.013']}
//         />
//       </group>
//       <group position={[214.415, 699.894, -807.797]} rotation={[Math.PI, -Math.PI / 2, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_9.geometry}
//           material={materials['Material.134']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh_9_1.geometry}
//           material={materials['[0045_Goldenrod]1.001']}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Shower_Door.geometry}
//         material={materials['barthroom Door']}
//         position={[229.496, 1585.084, -822.923]}
//         rotation={[0, 0, 0]}
//         scale={[1090.837, 1023.685, 852.67]}
//       />
//       <group
//         position={[484.413, 1052.139, -1929.938]}
//         rotation={[-3.129, 0, 0]}
//         scale={[-885.063, -976.599, -976.599]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_1.geometry}
//           material={materials.La}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_2.geometry}
//           material={materials['Material.022']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_3.geometry}
//           material={materials['Material.140']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_4.geometry}
//           material={materials['Material.143']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_5.geometry}
//           material={materials['Material.139']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_6.geometry}
//           material={materials['Material.137']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_7.geometry}
//           material={materials['brushed nickel']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_8.geometry}
//           material={materials['Material.141']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39002_9.geometry}
//           material={materials['black.001']}
//         />
//       </group>
//       <group
//         position={[213.319, 649.856, 663.505]}
//         rotation={[-Math.PI / 2, -1.558, Math.PI / 2]}
//         scale={[-885.063, -976.599, -976.599]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39001_1.geometry}
//           material={materials['Material.015']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39001_2.geometry}
//           material={materials['Material.016']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39001_3.geometry}
//           material={materials['red.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39001_4.geometry}
//           material={materials['chrome.001']}
//         />
//       </group>
//       <group
//         position={[-566.047, 1515.927, -926.465]}
//         rotation={[Math.PI, 0, Math.PI]}
//         scale={[931.117, 925.058, 925.058]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle004.geometry}
//           material={materials['InductionMat.003']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle004_1.geometry}
//           material={materials['black.005']}
//         />
//       </group>
//       <group
//         position={[-513.588, 952.528, -726.294]}
//         rotation={[0, -1.571, 0]}
//         scale={[1047.739, 1064.545, 1014.753]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002.geometry}
//           material={materials.Black_Matel}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002_1.geometry}
//           material={materials['Material.041']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002_2.geometry}
//           material={materials.Bleck_S}
//         />
//       </group>
//       <group position={[15.662, 1798.869, -1875.947]} scale={[823.714, 976.599, 1014.203]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018.geometry}
//           material={materials['Material.018']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018_1.geometry}
//           material={materials['Laminate_D02_120cm1.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018_2.geometry}
//           material={materials['[Color E04].002']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018_3.geometry}
//           material={materials['[Color M00]1.002']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018_4.geometry}
//           material={materials.Mate}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018_5.geometry}
//           material={materials.La}
//         />
//       </group>
//       <group position={[1.448, -166.742, 79.589]} scale={[1023.136, 1033.378, 1033.378]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Tir003_1.geometry}
//           material={materials.tire}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Tir003_2.geometry}
//           material={materials.brakedisk}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Tir003_3.geometry}
//           material={materials.rim}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Ladder001.geometry}
//         material={materials['Material.038']}
//         position={[1101.958, 1437.286, -1041.302]}
//         rotation={[1.58, -0.037, -1.57]}
//         scale={[1051.945, 1058.837, 1060.448]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bad_platform002.geometry}
//         material={materials.bad}
//         position={[63.198, 1733.674, -1896.796]}
//         scale={[823.714, 976.599, 1014.203]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane077.geometry}
//         material={materials['Material.001']}
//         position={[540.867, 2331.486, -56.101]}
//         rotation={[0, -Math.PI / 2, 0]}
//         scale={920.496}
//       />
//       <group
//         position={[540.309, 2332.499, -50.284]}
//         rotation={[0, -Math.PI / 2, 0]}
//         scale={897.025}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane064.geometry}
//           material={materials['Material.023']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane064_1.geometry}
//           material={materials.txt}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane064_2.geometry}
//           material={materials['Material.027']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane064_3.geometry}
//           material={materials['Material.029']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane064_4.geometry}
//           material={materials['Material.030']}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.defaultMaterial002.geometry}
//         material={materials['Material.032']}
//         position={[354.874, 2406.719, 160.386]}
//         rotation={[0, -Math.PI / 2, 0]}
//         scale={[983.734, 868.16, 983.734]}
//       />
//       <group
//         position={[389.578, 2132.019, 211.262]}
//         rotation={[Math.PI / 2, 0, Math.PI / 2]}
//         scale={3.703}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder003.geometry}
//           material={materials['Metal.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder003_1.geometry}
//           material={materials['Material.017']}
//         />
//       </group>
//       <group
//         position={[546.143, 2333.895, -106.654]}
//         rotation={[Math.PI, -0.018, Math.PI]}
//         scale={869.865}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020.geometry}
//           material={materials['Material.034']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_1.geometry}
//           material={materials['Material.035']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_2.geometry}
//           material={materials.Microwave}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_3.geometry}
//           material={materials['Material.036']}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Roof_Rack.geometry}
//         material={nodes.Roof_Rack.material}
//         position={[-6.748, 2674.844, -1588.518]}
//         rotation={[-3.123, -1.571, 0]}
//         scale={9.92}
//       />
//       <group position={[500.958, 982.402, -1126.708]} rotation={[0, -Math.PI / 2, 0]} scale={1000}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh001.geometry}
//           material={materials['Material.011']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh001_1.geometry}
//           material={materials['Material.012']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh001_2.geometry}
//           material={materials['[0048_PaleGoldenrod].001']}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/vanInventory.glb')

