
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/final.glb')
  console.log(nodes,"nodes")
  return (
    <group {...props} dispose={null}>
        {/* right door  */}
      <group position={[-53.412, 41.383, 109.16]} rotation={[0,45,0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass.geometry}
          material={materials.clearglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_2.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_3.geometry}
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_4.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_5.geometry}
          material={materials.interior_third}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_6.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_7.geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass_8.geometry}
          material={materials.mirror}
        />
      </group>
       {/* Left door  */}
      <group position={[56.682, 42.027, 109.748]} rotation={[0,-45,0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002.geometry}
          material={materials.clearglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_2.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_3.geometry}
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_4.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_5.geometry}
          material={materials.interior_third}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_6.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_7.geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_front_R_Glass002_8.geometry}
          material={materials.mirror}
        />
      </group>
      {/* slider door */}
      <group position={[-52.453, 49.934, -5]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.side_door_1.geometry}
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.side_door_2.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.side_door_3.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group position={[4.694, 42.101, 55.009]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_1.geometry}
          material={materials['carpaint.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_2.geometry}
          material={materials['black.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_3.geometry}
          material={materials.Galsss01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_4.geometry}
          material={materials['black.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_5.geometry}
          material={materials['chrome.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_6.geometry}
          material={materials.Floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_7.geometry}
          material={materials.redglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_8.geometry}
          material={materials.Bleck_S}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_9.geometry}
          material={materials['clearglass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_10.geometry}
          material={materials.LicPlate_yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_11.geometry}
          material={materials.LicPlate_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_12.geometry}
          material={materials.LicPlate_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_13.geometry}
          material={materials.LicPlate_white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_14.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_15.geometry}
          material={materials.interior_second}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_16.geometry}
          material={materials['Antique Wallnut (Gel Stain on Maple)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_17.geometry}
          material={materials['black.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_18.geometry}
          material={materials['interior_second.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_19.geometry}
          material={materials['interior_sixth.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_20.geometry}
          material={materials['black.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_21.geometry}
          material={materials['carpaint.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_22.geometry}
          material={materials.blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_23.geometry}
          material={materials.mattemetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_24.geometry}
          material={materials.GLASS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_25.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_26.geometry}
          material={materials['black.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_27.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_28.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_29.geometry}
          material={materials['black.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_30.geometry}
          material={materials['red.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_31.geometry}
          material={materials['black.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_32.geometry}
          material={materials['chrome.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_33.geometry}
          material={materials['chrome.003']}
        />
      </group>
      <group position={[1.639, -7.716, -3.383]} scale={0.106}>
        <mesh castShadow receiveShadow geometry={nodes.Tir003.geometry} material={materials.tire} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tir003_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tir003_2.geometry}
          material={materials.brakedisk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tir003_3.geometry}
          material={materials.rim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tir003_4.geometry}
          material={materials.chrome}
        />
      </group>
      <group position={[-47.1, 2.655, -176.386]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={materials['White (Gel Stain on Maple)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_1.geometry}
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_2.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_3.geometry}
          material={materials['blue.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_4.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_5.geometry}
          material={materials['yellow.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_6.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group position={[50.102, 3.166, -175.385]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005.geometry}
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_2.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_3.geometry}
          material={materials['LicPlate_yellow.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_4.geometry}
          material={materials['LicPlate_black.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_5.geometry}
          material={materials['LicPlate_blue.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_6.geometry}
          material={materials['LicPlate_white.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_7.geometry}
          material={materials['yellow.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_8.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_part10005_9.geometry}
          material={materials['White (Gel Stain on Maple)']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.boot_side.geometry}
        material={materials.carpaint}
        position={[8.476, 71.134, -71.061]}
        scale={0.106}
      />
      <group position={[6.028, 132.547, -65.84]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001'].geometry}
          material={materials['Ekran_Resmi_2020-07-10_11.50.07_kopyası']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_1'].geometry}
          material={materials['[Metal_Corrogated_Shiny]2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_2'].geometry}
          material={materials['Simple wood.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_3'].geometry}
          material={materials['Material.135']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_4'].geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_5'].geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_6'].geometry}
          material={materials['white.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_7'].geometry}
          material={materials.black_rubber}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_8'].geometry}
          material={materials['Metal_Mesh_Grid.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_9'].geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_10'].geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_11'].geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_12'].geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_13'].geometry}
          material={materials['New ac']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_14'].geometry}
          material={materials['Material.038']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Component#16001_15'].geometry}
          material={materials['black.006']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Reflector02.geometry}
        material={materials.chrome}
        position={[1.645, 35.255, 153.963]}
        scale={0.106}
      />
      <group position={[3.54, 32.581, -43.38]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_1.geometry}
          material={materials.clearglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_2.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_3.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_4.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_5.geometry}
          material={materials['black.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_6.geometry}
          material={materials['mattemetal.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp01_7.geometry}
          material={materials.orangeglass}
        />
      </group>
      <group position={[2.316, 79.742, -115.795]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials['black.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials['Galsss01.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dinette_windows004.geometry}
        material={materials['Galsss01.001']}
        position={[56.279, 79.836, -125.944]}
        scale={0.106}
      />
      <group position={[51.273, 77.964, -13.155]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials['black.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials['Galsss01.001']}
        />
      </group>
      <group position={[-55.277, 52.576, -88.83]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_support_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_support_2.geometry}
          material={materials['mattemetal.001']}
        />
      </group>
      <group position={[1.642, 72.588, 107.927]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_glass_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_glass_2.geometry}
          material={materials.mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_glass_3.geometry}
          material={materials.black}
        />
      </group>
      <group position={[39.211, 83.745, -35.774]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13.geometry}
          material={materials['Material.134']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_1.geometry}
          material={materials['White (Gel Stain on Maple).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_2.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_3.geometry}
          material={materials['[0045_Goldenrod]1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_4.geometry}
          material={materials.Cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_5.geometry}
          material={materials['Stormy Sea (DE 5817)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_6.geometry}
          material={materials['W Light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_7.geometry}
          material={materials['White (GEL STAIN ON MAPLE).002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_8.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13_9.geometry}
          material={materials['Wooden .002']}
        />
      </group>
      <group position={[1.802, 34.115, -127.966]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002.geometry}
          material={materials.La}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_1.geometry}
          material={materials['Antique Wallnut (Gel Stain on Maple)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_2.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_3.geometry}
          material={materials['Stained bamboo']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_4.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_5.geometry}
          material={materials['Material.140']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_6.geometry}
          material={materials['Material.143']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_7.geometry}
          material={materials['Material.139']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_8.geometry}
          material={materials['Material.137']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_9.geometry}
          material={materials['brushed nickel']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_10.geometry}
          material={materials['Material.141']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_11.geometry}
          material={materials['black.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_12.geometry}
          material={materials['[0045_Goldenrod]1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39002_13.geometry}
          material={materials['black.009']}
        />
      </group>
      <group position={[1.876, 84.238, -118.477]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials['Material.074']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_2.geometry}
          material={materials['Laminate_D02_120cm1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_3.geometry}
          material={materials['[Color E04].002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_4.geometry}
          material={materials['[Color M00]1.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_5.geometry}
          material={materials['Antique Wallnut (Gel Stain on Maple).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_6.geometry}
          material={materials.Mate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_7.geometry}
          material={materials['Bleck_S.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_8.geometry}
          material={materials['La.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_9.geometry}
          material={materials.bad}
        />
      </group>
      <group position={[-0.683, 129.716, -74.772]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={materials['Antique Wallnut (Gel Stain on Maple).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_1.geometry}
          material={materials['black.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_2.geometry}
          material={materials['W Light.001']}
        />
      </group>
      <group position={[-35.185, 79.13, -37.908]} scale={0.106}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh044.geometry} material={materials.CP} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_1.geometry}
          material={materials['Stormy Sea (DE 5817)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_2.geometry}
          material={materials['Bone China DEW 339']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_3.geometry}
          material={materials['White (Gel Stain on Maple).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_4.geometry}
          material={materials['Antique Wallnut (Gel Stain on Maple)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_5.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_6.geometry}
          material={materials['Stained bamboo']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh044_7.geometry}
          material={materials.Bleck_S}
        />
      </group>
      <group position={[-33.225, 60.438, -12.892]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['����������1'].geometry}
          material={materials['Stained bamboo.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['����������1_1'].geometry}
          material={materials['Metal.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['����������1_2'].geometry}
          material={materials['Stormy Sea (DE 5817).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['����������1_3'].geometry}
          material={materials['Material.074']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['����������1_4'].geometry}
          material={materials['Material.006']}
        />
      </group>
      <group position={[13.384, 50.585, 97.783]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_2.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_3.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_4.geometry}
          material={materials.clearglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_5.geometry}
          material={materials.interior_fourth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_6.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_7.geometry}
          material={materials['blue.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_8.geometry}
          material={materials.interior_seventh}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_9.geometry}
          material={materials.interior_sixth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_10.geometry}
          material={materials.interior_fifth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_11.geometry}
          material={materials.interior_third}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.indicator_panel_needle_part_12.geometry}
          material={materials['interior_second.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane077.geometry}
        material={materials['Material.011']}
        position={[22.14, 116.714, 1.174]}
        scale={0.106}
      />
      <group position={[23.958, 116.5, -8.774]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064_1.geometry}
          material={materials.txt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064_2.geometry}
          material={materials['Material.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064_3.geometry}
          material={materials['Material.029']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial002.geometry}
        material={materials['Material.032']}
        position={[22.377, 121.013, 1.36]}
        scale={0.106}
      />
      <group position={[25.917, 115.979, -12.382]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['Material.035']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials['Material.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials.Microwave}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_4.geometry}
          material={materials['Material.039']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_5.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_6.geometry}
          material={materials['Metal.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_7.geometry}
          material={materials['Material.017']}
        />
      </group>
      <group position={[-24.82, 37.627, -64.497]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Black_Matel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials['Bleck_S.001']}
        />
      </group>
      <group position={[-31.694, 68.519, -62.427]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials['InductionMat.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_1.geometry}
          material={materials['black.011']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_sink.geometry}
        material={materials['Stained bamboo.001']}
        position={[-30.755, 67.735, -24.115]}
        scale={0.106}
      />
      <group position={[14.809, 73.702, -39.827]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials['[0045_Goldenrod]1.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials['barthroom Door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_2.geometry}
          material={materials['black.008']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials['Material.001']}
        position={[38.323, 107.365, -34.614]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.white}
        position={[-33.71, 104.389, -41.993]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials['White (Gel Stain on Maple)']}
        position={[1.338, 75.672, -22.818]}
        scale={0.106}
      />
      <group position={[31.008, 30.707, -67.268]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials['[0048_PaleGoldenrod].001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.014']}
        position={[-74.315, -2461.456, 1238.273]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        material={materials.Floor}
        position={[4.694, 42.101, 55.009]}
        scale={0.106}
      />
    </group>
  )
}

useGLTF.preload('/final.glb')

