// Common/index.js
export { default as Heading2 } from './Headings/Heading2'
export { default as Heading3 } from './Headings/Heading3'
export { default as Heading1 } from './Headings/Heading1'
export { default as Heading4 } from './Headings/Heading4'
export { default as CustomLink } from './CustomLink/CustomLink'
export { default as SecondaryButton } from './Button/SecondaryButton'
export { default as PrimaryButton } from './Button/PrimaryButton'
export { default as ShareButton } from './Button/ShareButton'
export { default as Breadcrumb } from './Breadcrumb/Breadcrumb'
export { default as RichParagraph } from './Paragraph/RichParagraph'
export { default as ImageWithSkeleton } from './ImageWithSkeleton/ImageWithSkeleton'
export { default as HeroParagraph } from './Paragraph/HeroParagraph'
// export { default as Loader } from './Loader/Loader'