/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function BatteryNoHeat400(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/400-battery-no-heat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._400_battery_no_heat1.geometry}
        material={materials['400ap']}
        position={[0, -0.003, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.146}
      />
    </group>
  )
}

useGLTF.preload('/models/in-parts144/400-battery-no-heat.glb')