/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function CabinetLocks(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/CabinetLocks.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CabinetLock.geometry}
        material={materials.Lock}
      />
    </group>
  )
}

useGLTF.preload('/models/in-parts144/CabinetLocks.glb')