/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function ControlPanel(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/Control_Panel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Control_Panel.geometry}
        material={materials.CP}
        position={[0.279, 2.102, -0.641]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/models/in-parts144/Control_Panel.glb')