/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function PortableToilet(props) {
  const { nodes, materials } = useGLTF('models/in-parts144/Portable_toilet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5.geometry}
          material={materials.PT}
          position={[-1.919, 0, 18.696]}
          scale={2.318}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/in-parts144/Portable_toilet.glb')