/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function BatteryNoHeat200(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/200-battery-no-heat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.battery_no_heat1.geometry}
        material={materials.One}
        position={[0.01, 0.004, 0.079]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.991}
      />
    </group>
  )
}

useGLTF.preload('/models/in-parts144/200-battery-no-heat.glb')