/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Invertorcharger3000(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/Invertorcharger3000.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Invertor_charger_3000.geometry}
        material={materials['Invertor charger 3000']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/models/in-parts144/Invertorcharger3000.glb')
