/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function TallCabinetFridge(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/TallCabinetFridge.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.511, 1.547, -0.915]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29_1.geometry}
          material={materials.Material_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29_2.geometry}
          material={materials['lock.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/in-parts144/TallCabinetFridge.glb')
