/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function TallFridge(props) {
  const { nodes, materials } = useGLTF('/models/in-parts144/TallFridge.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.469, 1.818, -0.917]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['Brushed Aluminum']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['Brushed Steel Procedural.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_5.geometry}
          material={materials['Material.024']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/in-parts144/TallFridge.glb')